import { z } from "zod"

export const companySchema = z.object({
  companyName: z.string().min(1, { message: "Company name is required" }),
  address: z.string().min(1, { message: "Address is required" }),
  address2: z.string().optional(),
  city: z.string().min(1, { message: "City is required" }),
  country: z.string().min(1, { message: "Country is required" }),
  postcode: z.string().min(1, { message: "Postcode is required" }),
  contactEmail: z.string().email({ message: "Invalid email address" }),
  contactPhone: z.string().min(1, { message: "Contact phone is required" }),
  websiteUrl: z.string().url({ message: "Invalid website URL" }),
  registeredCompanyName: z.string().optional(),
  overrideCnSenderName: z.string().optional(),
  vatNumber: z.string().optional(),
  eoriNumber: z.string().optional(),
  iossNumber: z.string().optional(),
  grantPermissions: z.boolean().default(false),
  ukimsNumber: z.string().optional(),
  eoriNumberNi: z.string().optional(),
  declarationCategories: z.object({
    document: z.boolean().default(false),
    returnedGoods: z.boolean().default(false),
    gift: z.boolean().default(false),
    saleOfGoods: z.boolean().default(false),
    mixedContent: z.boolean().default(false),
    commercialSample: z.boolean().default(false),
    other: z.boolean().default(false),
  }),
  autoSignDeclarations: z.boolean().default(false),
  declarationFile: z.string().optional(),
  companyLogo: z.string().optional(),
})
